tasks:
  - name: create .env file
    command: |
      cp .env.example .env
  - name: run composer install
    command: |
      composer install
  - name: generate app key
    command: |
      php artisan key:generate
  - name: start app
    command: php artisan serve


